### ISSUE TITLE
Angular UI Bootstrap Typeahead and GSDP Animation are interfering

### ISSUE THREAD

**Issue by areindl** [timcreative/get-shit-done-pro#21]
Hi!

I just wanted to let you know that Typeahead module of Angular UI Bootstrap is interfering with the styled dropdown. It is know visible. I guess it is due to the custom animation that you apply to the dropdown of Bootstrap.

I workaround it quickly by adding:

```
#myTypeaheadContainer .dropdown-menu {
        opacity: 1 !important;
        visibility: visible;
      }  

`````

Can you tell me where I can disable or limit the behaviour of your animation code?

Thanks!

Best Regards,
Anton

**Comment by alexandru-paduraru** [comment]
Yes, you're right. We changed the behaviour of the dropdown in order to obtain the animation. 

If you go on gsdk.css, there is on line 4567 the css properties for the dropdown with animation on normal state and on 4580 the css properties for the dropdown with animation on the open state. If you remove those 2 properties there will be no animation at all on the dropdowns.

Let me know if that worked.

**Comment by areindl** [comment]
Got it! Thanks. That helped.
